name: SChool-API_Project_Login_Test_Execution

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./SchoolAPIProject/SchoolAPIProject.sln

      - name: Build project
        run: dotnet build ./SchoolAPIProject/SchoolAPIProject.sln --no-restore --configuration Release

      - name: Run Reqnroll tests
        run: dotnet test ./SchoolAPIProject/SchoolAPIProject.sln --no-build --configuration Release --filter Category=login || true

      - name: Find Report File
        id: find_report
        run: |
          $report = Get-ChildItem -Path ./SchoolAPIProject/SchoolAPIProject/bin/Release/net8.0/ -Filter "TestReport_*.html" | Select-Object -First 1
          echo "REPORT_NAME=$($report.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./SchoolAPIProject/SchoolAPIProject/bin/Release/net8.0/TestReport_*.html
          retention-days: 7
